modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="nolittering"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="nolittering.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config = "nolittering.mixins.json"
[[mixins]]
config = "nolittering.forge.mixins.json"
[[dependencies.nolittering]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.nolittering]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.nolittering]]
modId="balm"
mandatory=true
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
